# Generated by Django 5.2.7 on 2025-10-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unique_symbols', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('form_factor', models.CharField(max_length=50)),
                ('keys', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('keyboard_model', models.FileField(upload_to='keyboard_models/')),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=128)),
                ('layout_model', models.FileField(upload_to='layout_models/')),
            ],
        ),
        migrations.CreateModel(
            name='Bigramm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=2)),
                ('entrances', models.IntegerField()),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyboard_api.corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1)),
                ('entrances', models.IntegerField()),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyboard_api.corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_distance', models.FloatField()),
                ('travel_distance_finger_1', models.FloatField()),
                ('travel_distance_finger_2', models.FloatField()),
                ('travel_distance_finger_3', models.FloatField()),
                ('travel_distance_finger_4', models.FloatField()),
                ('travel_distance_finger_5', models.FloatField()),
                ('travel_distance_finger_6', models.FloatField()),
                ('travel_distance_finger_7', models.FloatField()),
                ('travel_distance_finger_8', models.FloatField()),
                ('travel_distance_finger_9', models.FloatField()),
                ('travel_distance_finger_10', models.FloatField()),
                ('hand_usage_left_hand', models.FloatField()),
                ('hand_usage_right_hand', models.FloatField()),
                ('finger_usage_1', models.FloatField()),
                ('finger_usage_2', models.FloatField()),
                ('finger_usage_3', models.FloatField()),
                ('finger_usage_4', models.FloatField()),
                ('finger_usage_5', models.FloatField()),
                ('finger_usage_6', models.FloatField()),
                ('finger_usage_7', models.FloatField()),
                ('finger_usage_8', models.FloatField()),
                ('finger_usage_9', models.FloatField()),
                ('finger_usage_10', models.FloatField()),
                ('row_usage_top', models.FloatField()),
                ('row_usage_home', models.FloatField()),
                ('row_usage_bottom', models.FloatField()),
                ('same_finger_bigrams_left_hand', models.FloatField()),
                ('same_finger_bigrams_right_hand', models.FloatField()),
                ('alternating_finger_bigrams_left_hand', models.FloatField()),
                ('alternating_finger_bigrams_right_hand', models.FloatField()),
                ('inrolls', models.FloatField()),
                ('outrolls', models.FloatField()),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyboard_api.corpus')),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyboard_api.keyboard')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyboard_api.layout')),
            ],
        ),
    ]
