# Generated by Django 5.2.7 on 2025-10-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='scissor_bigrams_left_hand',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='scissor_bigrams_right_hand',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corpus',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='form_factor',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='layout',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
