# Generated by Django 5.2.7 on 2025-11-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0002_metric_scissor_bigrams_left_hand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(upload_to='layout_previews/')),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyboard_api.keyboard')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyboard_api.layout')),
            ],
            options={
                'unique_together': {('layout', 'keyboard')},
            },
        ),
    ]
