# Generated by Django 5.2.7 on 2025-11-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0003_layoutpreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layoutpreview',
            old_name='preview_image',
            new_name='layout_preview',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='keyboard_preview',
            field=models.ImageField(default='None', upload_to='keyboard_previews/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layoutpreview',
            name='frequency_preview',
            field=models.ImageField(default='None', upload_to='frequency_previews/'),
            preserve_default=False,
        ),
    ]
