# Generated by Django 5.2.7 on 2025-11-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0004_rename_preview_image_layoutpreview_layout_preview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutpreview',
            name='frequency_preview',
        ),
        migrations.AddField(
            model_name='metric',
            name='frequency_heatmap',
            field=models.ImageField(default='None', upload_to='frequency_heatmaps/'),
            preserve_default=False,
        ),
    ]
