# Generated by Django 5.2.7 on 2025-11-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0005_remove_layoutpreview_frequency_preview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigramm',
            options={'verbose_name': 'биграмма', 'verbose_name_plural': 'биграммы'},
        ),
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name': 'корпус', 'verbose_name_plural': 'корпуса'},
        ),
        migrations.AlterModelOptions(
            name='frequency',
            options={'verbose_name': 'частота', 'verbose_name_plural': 'частоты'},
        ),
        migrations.AlterModelOptions(
            name='keyboard',
            options={'verbose_name': 'клавиатура', 'verbose_name_plural': 'клавиатуры'},
        ),
        migrations.AlterModelOptions(
            name='layout',
            options={'verbose_name': 'раскладка', 'verbose_name_plural': 'раскладки'},
        ),
        migrations.AlterModelOptions(
            name='layoutpreview',
            options={'verbose_name': 'превью раскладки', 'verbose_name_plural': 'превью раскладок'},
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'verbose_name': 'метрика', 'verbose_name_plural': 'метрики'},
        ),
        migrations.RemoveField(
            model_name='metric',
            name='hand_usage_left_hand',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='hand_usage_right_hand',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='row_usage_bottom',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='row_usage_home',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='row_usage_top',
        ),
        migrations.AddField(
            model_name='metric',
            name='row_usage_a',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='row_usage_b',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='row_usage_c',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='row_usage_d',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='row_usage_e',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='row_usage_k',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
