# Generated by Django 5.2.7 on 2025-11-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0006_alter_bigramm_options_alter_corpus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='corpus',
        ),
        migrations.DeleteModel(
            name='Bigramm',
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
    ]
