# Generated by Django 5.2.7 on 2025-11-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0007_remove_frequency_corpus_delete_bigramm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='alternating_finger_bigrams_left_hand',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='alternating_finger_bigrams_right_hand',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='inrolls',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='outrolls',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='same_finger_bigrams_left_hand',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='same_finger_bigrams_right_hand',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='scissor_bigrams_left_hand',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='scissor_bigrams_right_hand',
        ),
    ]
