# Generated by Django 5.2.7 on 2025-11-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0008_remove_metric_alternating_finger_bigrams_left_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='alternate_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='full_scissor_bigram_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='full_scissor_skipgram_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='half_scissor_bigram_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='half_scissor_skipgram_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='lateral_stretch_bigram_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='lateral_stretch_skipgram_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='onehand_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='redirect_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='roll_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='same_finger_bigram_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='same_finger_bigram_mean_distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='same_finger_skipgram_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='same_finger_skipgram_mean_distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
