# Generated by Django 5.2.7 on 2025-11-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0009_metric_alternate_frequency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('corpus', 'keyboard', 'layout')},
        ),
    ]
