# Generated by Django 5.2.7 on 2025-11-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0010_alter_metric_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='language',
            field=models.CharField(default='un', max_length=5),
            preserve_default=False,
        ),
    ]
