# Generated by Django 5.2.7 on 2025-11-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0011_corpus_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyboard',
            name='feacures',
            field=models.TextField(blank=True, null=True),
        ),
    ]
