# Generated by Django 5.2.7 on 2025-11-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0012_keyboard_feacures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyboard',
            old_name='feacures',
            new_name='features',
        ),
    ]
