# Generated by Django 5.2.7 on 2025-12-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard_api', '0013_rename_feacures_keyboard_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='features',
        ),
    ]
